name: Python test runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Check for test files
      id: check_test_files
      run: |
        if ls -1 tests/test_*.py > /dev/null 2>&1; then
          echo "TESTS_FOUND=true" >> $GITHUB_ENV
        else
          echo "TESTS_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Print TESTS_FOUND value
      run: echo "TESTS_FOUND is ${{ env.TESTS_FOUND }}"

    - name: Run tests
      if: ${{ env.TESTS_FOUND == 'true' }}
      run: |
        source venv/bin/activate
        pytest
